version: "3.9"

services:
  outbox-worker:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: outbox-worker
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
    command: "uvicorn --factory presentation.workers.main:create_app --host 0.0.0.0 --port 8001"
    env_file:
      - ../.env
    volumes:
      - ../app/:/app/
    networks:
      - backend

networks:
  backend:
    name: chat_backend
    driver: bridge
