version: "3.9"

services:
  outbox-worker:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: outbox-worker
    command: "uvicorn --factory presentation.workers.main:create_app --host 0.0.0.0 --port 8001"
    env_file:
      - ../.env
    volumes:
      - ../app/:/app/
    networks:
      - backend

networks:
  backend:
    external: true
    name: docker_compose_backend
