"""empty message

Revision ID: 4865b9bb1e71
Revises: 1c1963d8642d
Create Date: 2026-01-12 12:10:45.236222

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4865b9bb1e71"
down_revision: Union[str, Sequence[str], None] = "1c1963d8642d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "outbox_events",
        sa.Column(
            "event_type",
            sa.String(length=255),
            nullable=False,
            comment="Тип события (например, user.created)",
        ),
        sa.Column(
            "aggregate_type",
            sa.String(length=255),
            nullable=False,
            comment="Тип агрегата (например, user)",
        ),
        sa.Column(
            "aggregate_id", sa.String(length=255), nullable=False, comment="ID агрегата"
        ),
        sa.Column(
            "payload",
            sa.JSON(),
            nullable=False,
            comment="Данные события в формате JSON",
        ),
        sa.Column(
            "status",
            sa.String(length=50),
            nullable=False,
            comment="Статус обработки события",
        ),
        sa.Column(
            "processed_at",
            sa.String(length=255),
            nullable=True,
            comment="Время обработки события",
        ),
        sa.Column("oid", sa.UUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("oid"),
    )
    op.drop_column("users", "avatar_path")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "avatar_path", sa.VARCHAR(length=512), autoincrement=False, nullable=True
        ),
    )
    op.drop_table("outbox_events")
    # ### end Alembic commands ###
